import type { Metadata } from 'next'
import './globals.css'
import { pretendard } from '@/constants/fonts'
import { Header } from '@/components/Header'
import NextTopLoader from 'nextjs-toploader'
import { MainNavbar } from '@/components/MainNavbar'
import ModalWrapper from '@/components/modal/ModalWrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={pretendard.className}>
        <NextTopLoader />
        <div className="flex">
          <MainNavbar />
          <div className="flex-1">
            <Header />
            <ModalWrapper />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
